ScheduleIt2.0/ScheduleIt2.0/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ScheduleIt2._0.Controllers
{
    public class CalendarController : Controller
    {
        // GET: Calendar
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
    }
}

ScheduleIt2.0/ScheduleIt2.0/Controllers/TimeOffEventController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using ScheduleIt2._0.Models;

namespace ScheduleIt2._0.Controllers
{
    public class TimeOffEventController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: TimeOffEvent
        [Authorize]
        public ActionResult Index()
        {
            //return the list to be referenced in index view foreach block of code and ensure it won't be null by passing in db
            return View(db.TimeOffEvents.ToList());
        }

        // GET: TimeOffEvent/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TimeOffEvent timeOffEvent = db.TimeOffEvents.Find(id);
            if (timeOffEvent == null)
            {
                return HttpNotFound();
            }
            return View(timeOffEvent);
        }

        // GET: TimeOffEvent/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TimeOffEvent/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EventId,StartTime,EndTime,Message,Title,AdminId")] TimeOffEvent timeOffEvent)
        {
            if (ModelState.IsValid)
            {
                timeOffEvent.EventId = Guid.NewGuid();
                timeOffEvent.Submitted = DateTime.Now;
                db.TimeOffEvents.Add(timeOffEvent);
                db.SaveChanges();
                //Once the form has been submitted, return to home
                return View("~/Views/Home/Index.cshtml");
            }

            return View(timeOffEvent);
        }

        // GET: TimeOffEvent/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TimeOffEvent timeOffEvent = db.TimeOffEvents.Find(id);
            if (timeOffEvent == null)
            {
                return HttpNotFound();
            }
            return View(timeOffEvent);
        }

        // POST: TimeOffEvent/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EventId,StartTime,EndTime,Message,Title,AdminId")] TimeOffEvent timeOffEvent)
        {
            if (ModelState.IsValid)
            {
                db.Entry(timeOffEvent).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(timeOffEvent);
        }

        // GET: TimeOffEvent/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TimeOffEvent timeOffEvent = db.TimeOffEvents.Find(id);
            if (timeOffEvent == null)
            {
                return HttpNotFound();
            }
            return View(timeOffEvent);
        }

        // POST: TimeOffEvent/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            TimeOffEvent timeOffEvent = db.TimeOffEvents.Find(id);
            db.TimeOffEvents.Remove(timeOffEvent);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ScheduleIt2.0/ScheduleIt2.0/Views/Shared/_CalendarPartial.cshtml
<!--The Calendar-->
<div id="calendar"></div>
           

ScheduleIt2.0/ScheduleIt2.0/Views/Shared/_FooterPartial.cshtml
<p>&copy; Copyright @DateTime.Now.Year Schedule 2.0 The Tech Academy</p>
  

ScheduleIt2.0/ScheduleIt2.0/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/Site.css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <!--nav tag added and visible bar restored-->
        <!-- <div class="navbar navbar-dark bg-dark fixed-top navbar-expand-md">-->
        <!--UNNECESSARY^-->
        <div class="container">
            <!--<div class="navbar-header">--> <!--UNNECESSARY-->
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <!--aria controls added so login/registration button collapses too-->
                <span class="navbar-toggler-icon"></span> <!--added for toggle down menu in small screens-->
                <!--<span class="icon-bar"></span>
                <span class="icon-bar"></span>  UNNECESSARY
                <span class="icon-bar"></span>-->
            </button>
            <a href="@Url.Action("Index", "Home")" class="navbar-brand">
                <img src="~/Content/Logo.png" alt="Logo" style="width:110px;" />  <!--navbar tech academy logo-->
            </a>
            <!--</div>-->
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="@Url.Action("Index", "Home")">
                            <span class="fa-stack fa-2x">
                                <i class="fas fa-home fa-stack-1x fa-inverse" style="color:darkgoldenrod"></i>
                            </span>
                            @*Home*@
                        </a>
                    </li> <!--class="nav-item active mr-3" added too give links space-->
                    <li>
                        <a href="@Url.Action("About", "Home")">
                            <span class="fa-stack fa-2x">
                                <i class="fas fa-address-card fa-stack-1x fa-inverse" style="color:darkgoldenrod"></i>
                            </span>
                            @*About*@
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Contact", "Home")">
                            <span class="fa-stack fa-2x">
                                <i class="fas fa-envelope-square fa-stack-1x fa-inverse" style="color:darkgoldenrod"></i>
                            </span>
                            @*Contact*@
                        </a>
                    </li>

                    <li>
                        <a href="@Url.Action("Index", "Calendar")">
                            <span class="fa-stack fa-2x">
                                <i class="fa fa-calendar fa-stack-1x fa-inverse" style="color:darkgoldenrod"></i>
                            </span>
                            @*Calendar*@
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "TimeOffEvent")">
                            <span class="fa-stack fa-2x">
                                <i class="fa fa-plane-departure fa-stack-1x fa-inverse" style="color:darkgoldenrod"></i> 
                            </span> 
                        </a>
                    </li>


                </ul>
            </div>
            <span class="nav-text text-center">
                @Html.Partial("_LoginPartial") <!--moved to be on other side of navbar-->
            </span>
        </div>
        <!--</div>-->
    </nav>
    <div class="container body-content mt-5">
        <!--mt-5 added so any body content isn't right underneath the nav-->
        @RenderBody()
        <hr />
        <footer class="text-center">
            <!--Add Footer Partial view-->
            @Html.Partial("_FooterPartial")
        </footer>
        @*End FOOTER for layout*@
    </div>
    @Scripts.Render("~/bundles/jquery")
    <!--add boostrap for modal (kw)-->
    @Scripts.Render("~/bundles/bootstrap")

    <!--add fullcalendar bundle-->
    @Scripts.Render("~/bundles/fullcalendar")
    @RenderSection("scripts", required: false)
</body>
</html>